### ISSUE TITLE
Forgot to write this in Magma

### ISSUE THREAD

**Issue by ngregrichardson** [magfmur/Website#2]
Hi there seems to be an issue in your compiler for the website. I think that HTML/CSS/JS/Java/C/C++/Rust/Go/Python are extremely outdated tech and you seem to be using at least two of those.This is a production app so please rewrite it exclusively in Magma. This is outrageous.

**Comment by magfmur** [comment]
> Hi there seems to be an issue in your compiler for the website. I think that HTML/CSS/JS/Java/C/C++/Rust/Go/Python are extremely outdated tech and you seem to be using at least two of those.This is a production app so please rewrite it exclusively in Magma. This is outrageous.

Hi!

I will definitely review the tech behind this site and rewrite it to fit the needs of the world today.

Thank you for this contribution!
- Nate Stutte
